"""Docs Sync — bridge の WebhookTriggerCog を使った GitHub → Claude Code ドキュメント更新。

2つのモード:
- "🔄 docs-sync" (通常push): 英語ドキュメントの同期のみ（軽量・高速）
- "🔄 docs-sync-translate" (リリース時): 全言語翻訳（ja, zh-CN, ko, es, pt-BR, fr）

このファイルはプロンプト定義のみ。実行ロジックは claude_discord.cogs.webhook_trigger に委譲。
"""

from __future__ import annotations

from claude_discord.cogs.webhook_trigger import WebhookTrigger

_COMMON_HEADER = """\
You are a documentation maintainer for the claude-code-discord-bridge project.
The repository is at /home/ebi/claude-code-discord-bridge.

## Step 1: Pull latest changes

```bash
cd /home/ebi/claude-code-discord-bridge && git pull origin main
```

## Step 2: Analyze what changed

Run `git diff HEAD~1 HEAD --stat` and `git diff HEAD~1 HEAD` to understand what changed.

## Step 3: Update English documentation if needed

If **source code** (.py files) changed:
- Read the changed code and check if README.md or CONTRIBUTING.md need updates
- Update sections about features, architecture, configuration, etc. if the code changes affect them
- Keep documentation accurate and in sync with the code
- Do NOT update docs for trivial changes (formatting, comments, internal refactors that don't change behavior)
"""

_TRANSLATE_STEP = """\

## Step 4: Translate to all supported languages

Target languages (create docs/{lang}/ for each):
- `ja` — Japanese (日本語)
- `zh-CN` — Chinese Simplified (简体中文)
- `ko` — Korean (한국어)
- `es` — Spanish (Español)
- `pt-BR` — Portuguese - Brazil (Português)
- `fr` — French (Français)

For each English doc (README.md, CONTRIBUTING.md), create or update its translation in every language directory.

Translation rules:
1. Keep all markdown formatting, code blocks, links, and badges intact
2. Do NOT translate: code snippets, URLs, file paths, variable names, "claude-code-discord-bridge", common English tech terms (CLI, API, Cog, thread, session, subprocess, etc.)
3. DO translate: headings, descriptions, explanatory text, table headers/descriptions, comments, notes
4. Add a bilingual notice at the top of each translated file (in English + the target language):
   ```
   > **Note:** This is an auto-translated version of the original English documentation.
   > If there are any discrepancies, the [English version](../../README.md) takes precedence.
   > (同じ内容をその言語で)
   ```
5. Use natural, fluent language — not mechanical translation. Write as a native speaker would
6. For README.md, update relative links to point to same-language versions where they exist
"""

_TRANSLATE_JA_STEP = """\

## Step 4: Translate to Japanese

Update or create Japanese translations in `docs/ja/` for each English doc (README.md, CONTRIBUTING.md).

Translation rules:
1. Keep all markdown formatting, code blocks, links, and badges intact
2. Do NOT translate: code snippets, URLs, file paths, variable names, "claude-code-discord-bridge", common English tech terms (CLI, API, Cog, thread, session, subprocess, etc.)
3. DO translate: headings, descriptions, explanatory text, table headers/descriptions, comments, notes
4. Add a bilingual notice at the top:
   ```
   > **Note:** This is an auto-translated version of the original English documentation.
   > If there are any discrepancies, the [English version](../../README.md) takes precedence.
   > **注意:** これは英語のオリジナルドキュメントを自動翻訳したものです。
   > 内容に相違がある場合は、[英語版](../../README.md)が優先されます。
   ```
5. Use natural, fluent Japanese — not mechanical translation
6. Update relative links to point to Japanese versions where they exist
"""

_PR_STEP_SYNC = """\

## Step 5: Create a PR

If any documentation files were changed:

```bash
cd /home/ebi/claude-code-discord-bridge
git checkout -b docs-sync/$(date +%Y%m%d-%H%M%S)
git add -A
git commit -m "[docs-sync] Update documentation (English + Japanese)

Auto-generated by docs-sync workflow."
git push -u origin HEAD
gh pr create --title "[docs-sync] Update documentation (English + Japanese)" --body "Auto-generated documentation sync.

Changes:
- Updated English docs to reflect code changes (if applicable)
- Synchronized Japanese translation

This PR was automatically created by the docs-sync system."
```

If nothing changed, just report that docs are already up to date.

## Important
- NEVER modify source code (.py files) — only documentation (.md files)
- Commit messages MUST start with "[docs-sync]" to prevent infinite loops
- If unsure whether a code change needs doc updates, err on the side of NOT updating
"""

_PR_STEP_TRANSLATE = """\

## Step 5: Create a PR

If any files were changed:

```bash
cd /home/ebi/claude-code-discord-bridge
git checkout -b docs-sync/$(date +%Y%m%d-%H%M%S)
git add -A
git commit -m "[docs-sync] Update documentation and translations

Auto-generated by docs-sync workflow."
git push -u origin HEAD
gh pr create --title "[docs-sync] Update documentation and translations" --body "Auto-generated documentation sync.

Changes:
- Updated English docs to reflect code changes (if applicable)
- Synchronized translations (ja, zh-CN, ko, es, pt-BR, fr)

This PR was automatically created by the docs-sync system."
```

If nothing changed, just report that docs are already up to date.

## Important
- NEVER modify source code (.py files) — only documentation (.md files)
- Commit messages MUST start with "[docs-sync]" to prevent infinite loops
- If unsure whether a code change needs doc updates, err on the side of NOT updating
"""

# Assembled prompts
DOCS_SYNC_PROMPT = _COMMON_HEADER + _TRANSLATE_JA_STEP + _PR_STEP_SYNC
DOCS_TRANSLATE_PROMPT = _COMMON_HEADER + _TRANSLATE_STEP + _PR_STEP_TRANSLATE

# Trigger definitions for WebhookTriggerCog
BRIDGE_DIR = "/home/ebi/claude-code-discord-bridge"

DOCS_SYNC_TRIGGERS = {
    "🔄 docs-sync-translate": WebhookTrigger(
        prompt=DOCS_TRANSLATE_PROMPT,
        working_dir=BRIDGE_DIR,
        timeout=900,
    ),
    "🔄 docs-sync": WebhookTrigger(
        prompt=DOCS_SYNC_PROMPT,
        working_dir=BRIDGE_DIR,
        timeout=300,
    ),
}
