"""Docs Sync Cog — GitHub → Discord webhook trigger → Claude Code で翻訳・ドキュメント更新。

セキュリティ設計:
- Discord webhook メッセージ（webhook_id あり）のみ受け付ける
- 固定プレフィックス "🔄 docs-sync" のみ反応（それ以外は無視）
- 翻訳プロンプトはサーバー側にハードコード（webhook経由で注入不可）
- webhook URLが漏洩しても、翻訳が無駄に走るだけ（任意コマンド実行不可）
"""

from __future__ import annotations

import asyncio
import logging

import discord
from discord.ext import commands

from claude_discord.claude.runner import ClaudeRunner
from claude_discord.discord_ui.chunker import chunk_message
from claude_discord.discord_ui.embeds import error_embed

logger = logging.getLogger(__name__)

TRIGGER_PREFIX = "🔄 docs-sync"

DOCS_SYNC_PROMPT = """\
You are a documentation maintainer for the claude-code-discord-bridge project.
The repository is at /home/ebi/claude-code-discord-bridge.

## Step 1: Pull latest changes

```bash
cd /home/ebi/claude-code-discord-bridge && git pull origin main
```

## Step 2: Analyze what changed

Run `git diff HEAD~1 HEAD --stat` and `git diff HEAD~1 HEAD` to understand what changed.

## Step 3: Update English documentation if needed

If **source code** (.py files) changed:
- Read the changed code and check if README.md or CONTRIBUTING.md need updates
- Update sections about features, architecture, configuration, etc. if the code changes affect them
- Keep documentation accurate and in sync with the code
- Do NOT update docs for trivial changes (formatting, comments, internal refactors that don't change behavior)

## Step 4: Translate to all supported languages

Target languages (create docs/{lang}/ for each):
- `ja` — Japanese (日本語)
- `zh-CN` — Chinese Simplified (简体中文)
- `ko` — Korean (한국어)
- `es` — Spanish (Español)
- `pt-BR` — Portuguese - Brazil (Português)
- `fr` — French (Français)

For each English doc (README.md, CONTRIBUTING.md), create or update its translation in every language directory.

Translation rules:
1. Keep all markdown formatting, code blocks, links, and badges intact
2. Do NOT translate: code snippets, URLs, file paths, variable names, "claude-code-discord-bridge", common English tech terms (CLI, API, Cog, thread, session, subprocess, etc.)
3. DO translate: headings, descriptions, explanatory text, table headers/descriptions, comments, notes
4. Add a bilingual notice at the top of each translated file (in English + the target language):
   ```
   > **Note:** This is an auto-translated version of the original English documentation.
   > If there are any discrepancies, the [English version](../../README.md) takes precedence.
   > (同じ内容をその言語で)
   ```
5. Use natural, fluent language — not mechanical translation. Write as a native speaker would
6. For README.md, update relative links to point to same-language versions where they exist

## Step 5: Create a PR

If any files were changed:

```bash
cd /home/ebi/claude-code-discord-bridge
git checkout -b docs-sync/$(date +%Y%m%d-%H%M%S)
git add -A
git commit -m "[docs-sync] Update documentation and translations

Auto-generated by docs-sync workflow."
git push -u origin HEAD
gh pr create --title "[docs-sync] Update documentation and translations" --body "Auto-generated documentation sync.

Changes:
- Updated English docs to reflect code changes (if applicable)
- Synchronized translations (ja, zh-CN, ko, es, pt-BR, fr)

This PR was automatically created by the docs-sync system."
```

If nothing changed, just report that docs are already up to date.

## Important
- NEVER modify source code (.py files) — only documentation (.md files)
- Commit messages MUST start with "[docs-sync]" to prevent infinite loops
- If unsure whether a code change needs doc updates, err on the side of NOT updating
"""


class DocsSyncCog(commands.Cog):
    """Cog that handles automated documentation sync triggered by Discord webhooks."""

    def __init__(
        self,
        bot: commands.Bot,
        runner: ClaudeRunner,
        channel_id: int,
    ) -> None:
        self.bot = bot
        self.runner = runner
        self.channel_id = channel_id
        self._lock = asyncio.Lock()

    @commands.Cog.listener()
    async def on_message(self, message: discord.Message) -> None:
        """Handle webhook trigger messages."""
        # Only respond to webhook messages (not regular users, not bots)
        if not message.webhook_id:
            return

        # Only in the configured channel
        if message.channel.id != self.channel_id:
            return

        # Only respond to the specific trigger prefix
        if not message.content.startswith(TRIGGER_PREFIX):
            return

        logger.info(f"docs-sync トリガー受信: {message.content}")

        # Prevent concurrent runs
        if self._lock.locked():
            await message.reply("⏳ docs-sync は既に実行中です。スキップします。")
            return

        async with self._lock:
            await self._run_docs_sync(message)

    async def _run_docs_sync(self, trigger_message: discord.Message) -> None:
        """Run the docs sync process via Claude Code."""
        thread = await trigger_message.create_thread(name="📄 docs-sync")
        await thread.send("🔄 ドキュメント同期を開始します...")

        runner = ClaudeRunner(
            command=self.runner.command,
            model=self.runner.model,
            permission_mode="default",  # Full permissions for git operations
            working_dir="/home/ebi/claude-code-discord-bridge",
            timeout_seconds=600,  # 10 minutes max
        )

        accumulated_text = ""

        try:
            from claude_discord.claude.types import MessageType

            async for event in runner.run(DOCS_SYNC_PROMPT, session_id=None):
                if event.message_type == MessageType.ASSISTANT:
                    if event.text:
                        accumulated_text = event.text

                if event.is_complete:
                    if event.error:
                        await thread.send(embed=error_embed(event.error))
                        await trigger_message.add_reaction("❌")
                    else:
                        response_text = event.text or accumulated_text
                        if response_text:
                            for chunk in chunk_message(response_text):
                                await thread.send(chunk)
                        await trigger_message.add_reaction("✅")

        except Exception:
            logger.exception("docs-sync エラー")
            await thread.send(embed=error_embed("docs-sync でエラーが発生しました。"))
            await trigger_message.add_reaction("❌")
