"""Docs Sync Cog — GitHub → Discord webhook trigger → Claude Code でドキュメント更新。

2つのモード:
- "🔄 docs-sync" (通常push): 英語ドキュメントの同期のみ（軽量・高速）
- "🔄 docs-sync-translate" (リリース時): 全言語翻訳（ja, zh-CN, ko, es, pt-BR, fr）

セキュリティ設計:
- Discord webhook メッセージ（webhook_id あり）のみ受け付ける
- 固定プレフィックス "🔄 docs-sync" のみ反応（それ以外は無視）
- プロンプトはサーバー側にハードコード（webhook経由で注入不可）
- webhook URLが漏洩しても、同期が無駄に走るだけ（任意コマンド実行不可）
"""

from __future__ import annotations

import asyncio
import logging

import discord
from discord.ext import commands

from claude_discord.claude.runner import ClaudeRunner
from claude_discord.cogs._run_helper import run_claude_in_thread

logger = logging.getLogger(__name__)

TRIGGER_SYNC = "🔄 docs-sync"
TRIGGER_TRANSLATE = "🔄 docs-sync-translate"

_COMMON_HEADER = """\
You are a documentation maintainer for the claude-code-discord-bridge project.
The repository is at /home/ebi/claude-code-discord-bridge.

## Step 1: Pull latest changes

```bash
cd /home/ebi/claude-code-discord-bridge && git pull origin main
```

## Step 2: Analyze what changed

Run `git diff HEAD~1 HEAD --stat` and `git diff HEAD~1 HEAD` to understand what changed.

## Step 3: Update English documentation if needed

If **source code** (.py files) changed:
- Read the changed code and check if README.md or CONTRIBUTING.md need updates
- Update sections about features, architecture, configuration, etc. if the code changes affect them
- Keep documentation accurate and in sync with the code
- Do NOT update docs for trivial changes (formatting, comments, internal refactors that don't change behavior)
"""

_TRANSLATE_STEP = """\

## Step 4: Translate to all supported languages

Target languages (create docs/{lang}/ for each):
- `ja` — Japanese (日本語)
- `zh-CN` — Chinese Simplified (简体中文)
- `ko` — Korean (한국어)
- `es` — Spanish (Español)
- `pt-BR` — Portuguese - Brazil (Português)
- `fr` — French (Français)

For each English doc (README.md, CONTRIBUTING.md), create or update its translation in every language directory.

Translation rules:
1. Keep all markdown formatting, code blocks, links, and badges intact
2. Do NOT translate: code snippets, URLs, file paths, variable names, "claude-code-discord-bridge", common English tech terms (CLI, API, Cog, thread, session, subprocess, etc.)
3. DO translate: headings, descriptions, explanatory text, table headers/descriptions, comments, notes
4. Add a bilingual notice at the top of each translated file (in English + the target language):
   ```
   > **Note:** This is an auto-translated version of the original English documentation.
   > If there are any discrepancies, the [English version](../../README.md) takes precedence.
   > (同じ内容をその言語で)
   ```
5. Use natural, fluent language — not mechanical translation. Write as a native speaker would
6. For README.md, update relative links to point to same-language versions where they exist
"""

_TRANSLATE_JA_STEP = """\

## Step 4: Translate to Japanese

Update or create Japanese translations in `docs/ja/` for each English doc (README.md, CONTRIBUTING.md).

Translation rules:
1. Keep all markdown formatting, code blocks, links, and badges intact
2. Do NOT translate: code snippets, URLs, file paths, variable names, "claude-code-discord-bridge", common English tech terms (CLI, API, Cog, thread, session, subprocess, etc.)
3. DO translate: headings, descriptions, explanatory text, table headers/descriptions, comments, notes
4. Add a bilingual notice at the top:
   ```
   > **Note:** This is an auto-translated version of the original English documentation.
   > If there are any discrepancies, the [English version](../../README.md) takes precedence.
   > **注意:** これは英語のオリジナルドキュメントを自動翻訳したものです。
   > 内容に相違がある場合は、[英語版](../../README.md)が優先されます。
   ```
5. Use natural, fluent Japanese — not mechanical translation
6. Update relative links to point to Japanese versions where they exist
"""

_PR_STEP_SYNC = """\

## Step 5: Create a PR

If any documentation files were changed:

```bash
cd /home/ebi/claude-code-discord-bridge
git checkout -b docs-sync/$(date +%Y%m%d-%H%M%S)
git add -A
git commit -m "[docs-sync] Update documentation (English + Japanese)

Auto-generated by docs-sync workflow."
git push -u origin HEAD
gh pr create --title "[docs-sync] Update documentation (English + Japanese)" --body "Auto-generated documentation sync.

Changes:
- Updated English docs to reflect code changes (if applicable)
- Synchronized Japanese translation

This PR was automatically created by the docs-sync system."
```

If nothing changed, just report that docs are already up to date.

## Important
- NEVER modify source code (.py files) — only documentation (.md files)
- Commit messages MUST start with "[docs-sync]" to prevent infinite loops
- If unsure whether a code change needs doc updates, err on the side of NOT updating
"""

_PR_STEP_TRANSLATE = """\

## Step 5: Create a PR

If any files were changed:

```bash
cd /home/ebi/claude-code-discord-bridge
git checkout -b docs-sync/$(date +%Y%m%d-%H%M%S)
git add -A
git commit -m "[docs-sync] Update documentation and translations

Auto-generated by docs-sync workflow."
git push -u origin HEAD
gh pr create --title "[docs-sync] Update documentation and translations" --body "Auto-generated documentation sync.

Changes:
- Updated English docs to reflect code changes (if applicable)
- Synchronized translations (ja, zh-CN, ko, es, pt-BR, fr)

This PR was automatically created by the docs-sync system."
```

If nothing changed, just report that docs are already up to date.

## Important
- NEVER modify source code (.py files) — only documentation (.md files)
- Commit messages MUST start with "[docs-sync]" to prevent infinite loops
- If unsure whether a code change needs doc updates, err on the side of NOT updating
"""

# Assembled prompts
DOCS_SYNC_PROMPT = _COMMON_HEADER + _TRANSLATE_JA_STEP + _PR_STEP_SYNC
DOCS_TRANSLATE_PROMPT = _COMMON_HEADER + _TRANSLATE_STEP + _PR_STEP_TRANSLATE


class DocsSyncCog(commands.Cog):
    """Cog that handles automated documentation sync triggered by Discord webhooks."""

    def __init__(
        self,
        bot: commands.Bot,
        runner: ClaudeRunner,
        channel_id: int,
    ) -> None:
        self.bot = bot
        self.runner = runner
        self.channel_id = channel_id
        self._lock = asyncio.Lock()

    @commands.Cog.listener()
    async def on_message(self, message: discord.Message) -> None:
        """Handle webhook trigger messages."""
        # Only respond to webhook messages (not regular users, not bots)
        if not message.webhook_id:
            return

        # Only in the configured channel
        if message.channel.id != self.channel_id:
            return

        # Determine mode from trigger message
        content = message.content.strip()
        if content == TRIGGER_TRANSLATE:
            prompt = DOCS_TRANSLATE_PROMPT
            mode = "translate"
        elif content.startswith(TRIGGER_SYNC):
            prompt = DOCS_SYNC_PROMPT
            mode = "sync"
        else:
            return

        logger.info(f"docs-sync トリガー受信 (mode={mode}): {content}")

        # Prevent concurrent runs
        if self._lock.locked():
            await message.reply("⏳ docs-sync は既に実行中です。スキップします。")
            return

        async with self._lock:
            await self._run_docs_sync(message, prompt, mode)

    async def _run_docs_sync(
        self,
        trigger_message: discord.Message,
        prompt: str,
        mode: str,
    ) -> None:
        """Run the docs sync process via Claude Code using the shared run helper."""
        label = "📄 docs-sync" if mode == "sync" else "🌐 docs-translate"
        thread = await trigger_message.create_thread(name=label)

        if mode == "sync":
            await thread.send("🔄 ドキュメント同期を開始します（英語 + 日本語）...")
        else:
            await thread.send("🌐 全言語翻訳を開始します（数分かかります）...")

        timeout = 300 if mode == "sync" else 900  # 5min for sync, 15min for translate

        runner = ClaudeRunner(
            command=self.runner.command,
            model=self.runner.model,
            permission_mode="default",
            working_dir="/home/ebi/claude-code-discord-bridge",
            timeout_seconds=timeout,
            dangerously_skip_permissions=True,  # Automated workflow — prompt is hardcoded server-side
        )

        # Use shared run helper — same rich experience as interactive sessions
        # (streaming text, tool embeds with results, thinking, intermediate text)
        # repo=None because automated workflows don't need session persistence
        session_id = await run_claude_in_thread(
            thread=thread,
            runner=runner,
            repo=None,
            prompt=prompt,
            session_id=None,
            status=None,
        )

        # Add reaction to the trigger message based on result
        if session_id:
            await trigger_message.add_reaction("✅")
        else:
            await trigger_message.add_reaction("❌")
